### ISSUE TITLE
Неверный параметр cascade = CascadeType.ALL

### ISSUE THREAD

**Issue by Folko85** [Kojanni/hibernate#1]
В классе Course связь ManyToOne с классом Teacher задана с параметром cascade = CascadeType.ALL. Это значит, что при удалении курса удалится и связанный с ним преподаватель. Поскольку преподаватель может вести много курсов, то использовать в данном случае CascadeType.ALL нежелательно.

**Comment by Kojanni** [comment]
Да, спасибо)
